# Generated by Django 2.2.1 on 2019-05-07 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('sets', models.PositiveSmallIntegerField()),
                ('repetitions', models.PositiveSmallIntegerField()),
                ('rate_of_perceived_exertion', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('percent_of_one_rep_max', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('date', models.DateField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workout Post',
                'verbose_name_plural': 'Workout posts',
            },
        ),
    ]
