# Generated by Django 2.2.1 on 2019-05-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='load',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
