# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-27 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='travel_end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='travel_start_date',
            field=models.DateField(),
        ),
    ]
